tests- Adding conformance results for 8.5 release
FRRouting/frr-www pull request #43
Opened 2023-05-03 07:35 UTC by vijaykug

Added 8.5 release conformance result for protocol - IGMP , IGMPv2, PIM, PIMv6
Added MLDv1 conformance result 

Signed-off-by:  vijaykug <vijayg@vmware.com>

2023-05-04 04:18 UTC, mobash-rasool approved these changes

2023-05-04 05:51 UTC, ton31337 reviewed
Where is this file `static/test-results/MLDv1_extended_results.pdf` used? I don't see any pointer to this file.

2023-05-04 06:48 UTC, vijaykug commented
> Where is this file `static/test-results/MLDv1_extended_results.pdf` used? I don't see any pointer to this file.

We are adding MLDv1 protocol conformance result first time , accordingly we need to edit wiki and website also .
Once this is merge , we will request to edit same.

2023-05-04 07:06 UTC, patrasar approved these changes

2023-05-05 10:48 UTC, mwinter-osr requested changes
First pass of review. Will still need to review the results (comparing against what I have, but please fix the PDFs to give actual git sha, so I can do the compare.

2023-05-05 10:48 UTC, mwinter-osr commented on static/test-results/MLDv1_extended_results.pdf
Listening verison as "8.5-dev" with no sha and no date is useless. Please add git sha for tested release and git date of the sha.

2023-05-05 10:48 UTC, mwinter-osr commented on static/test-results/IGMPv2_extended_results.pdf
Please don't give git sha as "released". Provide the actual sha of the tested code.

2023-05-05 10:48 UTC, mwinter-osr commented on static/test-results/IGMPv3_extended_results.pdf
Please don't give git sha as "released". Provide the actual sha of the tested code. Also, the date for the 8.4.2 code is wrong if this is actually the release code. 8.4.2 was tagged on Jan 9, 2023. You list Jan 11. Even assuming some random timzeone, this isn't possible.

2023-05-05 10:48 UTC, mwinter-osr commented on static/test-results/PIM_extended_results.pdf
Please don't give git sha as "released". Provide the actual sha of the tested code.

2023-05-05 10:48 UTC, mwinter-osr commented on static/test-results/PIMv6_extended_results.pdf
Please don't give git sha as "released". Provide the actual sha of the tested code.

2023-05-30 08:04 UTC, vijaykug commented
@mwinter-osr  I have added git sha's in all the PDF  , please review 
thanks

2023-06-02 10:14 UTC, mwinter-osr requested changes
Mostly good, except MLDv1 doesn't show results for a release, just a 9.0 dev branch. I prefer to not publish the dev branches on the frrouting.org website (but feel free to push them to github wiki).
Not sure if this is an error and you created the wrong PDF. Please either replace with a PDF with results from a release or remove the PDF for MLDv1.
Also, not seeing anything for MLDv2. Ok, if you don't have it yet, but if you do, then it would be nice to include as well.
Reviewed the content of the files (test results) and they mostly match mine, so content is verified and ok (for the releases).

Changes required:
- Either replace MLDv1 results with a file which shows results for the releases or remove the file until you have results with releases
- Add MLDv2 if you have it already

2023-06-02 12:38 UTC, vijaykug commented
> Mostly good, except MLDv1 doesn't show results for a release, just a 9.0 dev branch. I prefer to not publish the dev branches on the frrouting.org website (but feel free to push them to github wiki). Not sure if this is an error and you created the wrong PDF. Please either replace with a PDF with results from a release or remove the PDF for MLDv1. Also, not seeing anything for MLDv2. Ok, if you don't have it yet, but if you do, then it would be nice to include as well. Reviewed the content of the files (test results) and they mostly match mine, so content is verified and ok (for the releases).
> 
> Changes required:
> 
> * Either replace MLDv1 results with a file which shows results for the releases or remove the file until you have results with releases
> * Add MLDv2 if you have it already

Hi @mwinter-osr  , 
 I have removed MLDv1 PDF for now , will run MLD in next release (which will have the fixes ) 
 We do not have MLDv2 ANVL license , we are working on it  , will keep you posted

2023-06-02 13:52 UTC, mwinter-osr commented
> Hi @mwinter-osr , I have removed MLDv1 PDF for now , will run MLD in next release (which will have the fixes ) We do not have MLDv2 ANVL license , we are working on it , will keep you posted

I still see the MLDv1 PDF included in the PR.

2023-06-05 09:28 UTC, vijaykug commented
> > Hi @mwinter-osr , I have removed MLDv1 PDF for now , will run MLD in next release (which will have the fixes ) We do not have MLDv2 ANVL license , we are working on it , will keep you posted
> 
> I still see the MLDv1 PDF included in the PR.

@mwinter-osr   have correct and push the changes now , please check , thanks

2023-06-05 09:29 UTC, mwinter-osr approved these changes

2023-06-05 09:29 UTC, merged

2023-06-05 10:55 UTC, vijaykug commented
Hi @mwinter-osr  , could you please help updating result is frrouting wikki page also 
Thanks
Vijay