Release 10.0.1, 9.1.1, 9.0.3, 8.5.5, and 8.4.5
FRRouting/frr-www pull request #71
Opened 2024-06-06 23:40 UTC by Jafaral

2024-06-07 06:25 UTC, ton31337 requested changes

2024-06-07 06:25 UTC, ton31337 commented on content/release/10.0.1.md
> +=============================================
Could you align `=` with the title?

2024-06-07 06:25 UTC, ton31337 commented on content/release/10.0.1.md
> +- [CVE-2024-31951](https://frrouting.org/security/cve-2024-31951)
Shouldn't we include also these: CVE-2024-34088, CVE-2024-31949, CVE-2024-31948, CVE-2024-27913?

2024-06-07 06:25 UTC, ton31337 commented on content/release/10.0.1.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-10.0.1...frr-10.0.1.1
I think this should be `https://github.com/FRRouting/frr/compare/frr-10.0...frr-10.0.1`

2024-06-07 06:25 UTC, ton31337 commented on content/release/8.4.5.md
> +* Fix #11808 to avoid infinite loops
This link leads to nowhere.

2024-06-07 06:25 UTC, ton31337 commented on content/release/10.0.1.md
> +FRR 10.0.1 brings a long list of enhancements and fixes with 938 commits from 54 developers. Thanks to all contributors.
Is this an updated info?

2024-06-07 06:25 UTC, ton31337 commented on content/release/10.0.1.md
> +Docker - [quay.io/frrouting/frr:10.0.1](https://quay.io/repository/frrouting/frr/manifest/sha256:572c60d3d678887bbd97281e7995a976f7eceeb7f40bf43a13cbd7905d52af41)
The link needs to be updated after the images are built.

2024-06-07 06:25 UTC, ton31337 commented on content/release/8.4.5.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-8.4.4...frr-4.4.5
Wrong link.

2024-06-07 06:25 UTC, ton31337 commented on content/release/8.5.5.md
> +============================================
Also, please align with the title.

2024-06-07 06:25 UTC, ton31337 commented on content/release/9.0.3.md
> +============================================
Ditto.

2024-06-07 06:25 UTC, ton31337 commented on content/release/9.0.3.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-9.0.3...frr-9.0.3
Wrong link.

2024-06-07 06:25 UTC, ton31337 commented on content/release/9.1.1.md
> +============================================
Ditto.

2024-06-07 06:25 UTC, ton31337 commented on content/release/9.1.1.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-9.1.1...frr-9.1.1.1
Wrong link.

2024-06-10 14:52 UTC, Jafaral commented on content/release/8.4.5.md
> +* Fix #11808 to avoid infinite loops
This isn't a link, just a PR number, whatever was there in the original PR comment

2024-06-25 14:54 UTC, ton31337 commented on content/release/10.0.1.md
> +Docker - [quay.io/frrouting/frr:10.0.1](https://quay.io/repository/frrouting/frr/manifest/sha256:572c60d3d678887bbd97281e7995a976f7eceeb7f40bf43a13cbd7905d52af41)
https://quay.io/repository/frrouting/frr/manifest/sha256:8ab9fe2ded0be732634bbd9a38e69c72ad450c7c9c41289b05a5ae7e26fdbe8b

2024-06-25 14:55 UTC, ton31337 commented on content/release/9.1.1.md
> +Docker - [quay.io/frrouting/frr:9.1.1](https://quay.io/repository/frrouting/frr/manifest/sha256:)
https://quay.io/repository/frrouting/frr/manifest/sha256:0634cca8750c3ed2122a4bc79d65c932b091d1afba19dd617cd66a4adf923db3

2024-06-26 05:28 UTC, ton31337 reviewed
Missing some comments yet

2024-06-26 05:28 UTC, ton31337 commented on content/release/9.0.3.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-9.0.3...frr-9.0.3
Wrong still

2024-06-26 05:28 UTC, ton31337 commented on content/release/9.1.1.md
> +**Full Changelog**: https://github.com/FRRouting/frr/compare/frr-9.1.1...frr-9.1.1.1
Still wrong

2024-06-27 07:49 UTC, merged